version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Build phase complete
  post_build:
    commands:
      - echo Build successful
artifacts:
  files:
    - '**/*'
