version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - echo Build completed successfully!

  post_build:
    commands:
      - echo Packaging application...
      - zip -r deploy.zip * .[^.]*

artifacts:
  files:
    - deploy.zip
